export const RISK_LEVELS = ['low', 'mild', 'moderate', 'high', 'critical'] as const;
export type RiskLevel = (typeof RISK_LEVELS)[number];

export const SEVERITY_LEVELS = ['low', 'medium', 'high', 'critical'] as const;
export type SeverityLevel = (typeof SEVERITY_LEVELS)[number];

export const DARK_PATTERN_CATEGORIES = [
  'fake_urgency',
  'fake_scarcity',
  'fake_countdown',
  'confirmshaming',
  'preselected_consent',
  'forced_consent',
  'hidden_opt_out',
  'difficult_opt_out',
  'hidden_fees',
  'drip_pricing',
  'bait_and_switch',
  'misleading_button_hierarchy',
  'disguised_ads',
  'sneaking_into_cart',
  'subscription_traps',
  'difficult_cancellation',
  'roach_motel',
  'privacy_invasive_defaults',
  'excessive_data_collection',
  'ambiguous_consent',
  'bundled_consent',
  'third_party_tracking',
  'manipulative_social_proof',
  'repeated_interruption',
  'navigation_interference',
  'hidden_rejection_controls',
  'unclear_data_retention',
  'unclear_data_sharing',
  'prechecked_marketing',
  'accept_reject_imbalance',
] as const;
export type DarkPatternCategory = (typeof DARK_PATTERN_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<DarkPatternCategory, string> = {
  fake_urgency: 'Fake Urgency',
  fake_scarcity: 'Fake Scarcity',
  fake_countdown: 'Fake Countdown Timer',
  confirmshaming: 'Confirmshaming',
  preselected_consent: 'Preselected Consent',
  forced_consent: 'Forced Consent',
  hidden_opt_out: 'Hidden Opt-Out',
  difficult_opt_out: 'Difficult Opt-Out',
  hidden_fees: 'Hidden Fees',
  drip_pricing: 'Drip Pricing',
  bait_and_switch: 'Bait and Switch',
  misleading_button_hierarchy: 'Misleading Button Hierarchy',
  disguised_ads: 'Disguised Advertisement',
  sneaking_into_cart: 'Sneaking Items Into Cart',
  subscription_traps: 'Subscription Trap',
  difficult_cancellation: 'Difficult Cancellation',
  roach_motel: 'Roach Motel Pattern',
  privacy_invasive_defaults: 'Privacy-Invasive Defaults',
  excessive_data_collection: 'Excessive Data Collection',
  ambiguous_consent: 'Ambiguous Consent',
  bundled_consent: 'Bundled Consent',
  third_party_tracking: 'Third-Party Tracking',
  manipulative_social_proof: 'Manipulative Social Proof',
  repeated_interruption: 'Repeated Interruption',
  navigation_interference: 'Navigation Interference',
  hidden_rejection_controls: 'Hidden Rejection Controls',
  unclear_data_retention: 'Unclear Data Retention',
  unclear_data_sharing: 'Unclear Data Sharing',
  prechecked_marketing: 'Prechecked Marketing Consent',
  accept_reject_imbalance: 'Accept / Reject Imbalance',
};

export const RISK_SCORE_THRESHOLDS = {
  LOW: { min: 0, max: 19, label: 'LOW' as const },
  MILD: { min: 20, max: 39, label: 'MILD' as const },
  MODERATE: { min: 40, max: 59, label: 'MODERATE' as const },
  HIGH: { min: 60, max: 79, label: 'HIGH' as const },
  CRITICAL: { min: 80, max: 100, label: 'CRITICAL' as const },
} as const;

export const DEFAULT_USER_SETTINGS = {
  auto_scan: true,
  ai_analysis: true,
  telemetry_enabled: false,
  sensitive_page_protection: true,
  show_low_confidence: false,
  risk_notification_threshold: 60,
  retention_days: 30,
};

export const SENSITIVE_PATTERNS = {
  URL_KEYWORDS: [
    'login',
    'signin',
    'sign-in',
    'auth',
    'oauth',
    'bank',
    'banking',
    'chase.com',
    'wellsfargo.com',
    'bankofamerica.com',
    'healthcare',
    'patient',
    'mychart',
    'health',
    'medical',
    'password',
    'bitwarden',
    '1password',
    'lastpass',
    'gov',
    'irs.gov',
    'ssa.gov',
    'id.me',
    'checkout/payment',
  ],
  PAGE_TITLES: [
    'sign in',
    'log in',
    'internet banking',
    'patient portal',
    'password manager',
    'identity verification',
    'payment details',
  ],
  INPUT_TYPES: ['password', 'hidden'],
};
